# Generated by Django 4.1.7 on 2023-02-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0002_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='abc@bc.com', max_length=25),
            preserve_default=False,
        ),
    ]
