# Generated by Django 4.1.7 on 2023-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0003_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='aaa', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state',
            field=models.CharField(default='bbb', max_length=25),
            preserve_default=False,
        ),
    ]
