# Generated by Django 4.1.7 on 2023-02-24 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realstateapp', '0004_userinfo_city_userinfo_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='real_estate_adds',
            old_name='addvertiser_national_number',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='real_estate_adds',
            name='city',
        ),
        migrations.RemoveField(
            model_name='real_estate_adds',
            name='estate_number',
        ),
        migrations.RemoveField(
            model_name='real_estate_adds',
            name='estate_type',
        ),
        migrations.RemoveField(
            model_name='real_estate_adds',
            name='location',
        ),
        migrations.RemoveField(
            model_name='real_estate_adds',
            name='number_of_facilities',
        ),
        migrations.RemoveField(
            model_name='real_estate_adds',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='real_estate_adds',
            name='state',
        ),
        migrations.AddField(
            model_name='real_estate',
            name='city',
            field=models.CharField(default='khartoum', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate',
            name='estate_description',
            field=models.CharField(default='any decription', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate',
            name='location',
            field=models.TextField(default='abo adam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate',
            name='number_of_facilities',
            field=models.IntegerField(default=213),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate',
            name='optional_details',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='real_estate',
            name='state',
            field=models.CharField(default='Khartoum', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate_adds',
            name='addvertiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate_adds',
            name='real_estate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realstateapp.real_estate'),
            preserve_default=False,
        ),
    ]
