# Generated by Django 4.1.7 on 2023-02-26 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realstateapp', '0006_alter_userinfo_national_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='real_estate',
            old_name='estate_number',
            new_name='price',
        ),
        migrations.AddField(
            model_name='real_estate',
            name='addvertiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='real_estate_adds',
        ),
    ]
