# Generated by Django 4.1.7 on 2023-02-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0007_rename_estate_number_real_estate_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='authentication_image',
            field=models.ImageField(default=111, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate',
            name='estate_image1',
            field=models.ImageField(default=1111, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate',
            name='estate_image2',
            field=models.ImageField(default=111, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate',
            name='estate_image3',
            field=models.ImageField(default=111, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate',
            name='map_location',
            field=models.CharField(default='111111111', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='optional_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
