# Generated by Django 4.1.7 on 2023-02-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0008_real_estate_authentication_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='estate_status',
            field=models.CharField(choices=[('Waitting', 'Waitting'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Waitting', max_length=25),
        ),
    ]
