# Generated by Django 4.1.7 on 2023-03-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0010_alter_userinfo_email_alter_userinfo_national_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civil_registry',
            name='national_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
