# Generated by Django 4.1.7 on 2023-03-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0012_image_realestate_rename_civil_registry_civilregistry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='forth_name',
            new_name='forthName',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='second_name',
            new_name='secondName',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='third_name',
            new_name='thirdName',
        ),
    ]
