# Generated by Django 4.1.7 on 2023-03-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0013_rename_first_name_userinfo_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civilregistry',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='civilregistry',
            old_name='forth_name',
            new_name='forthName',
        ),
        migrations.RenameField(
            model_name='civilregistry',
            old_name='second_name',
            new_name='secondName',
        ),
        migrations.RenameField(
            model_name='civilregistry',
            old_name='third_name',
            new_name='thirdName',
        ),
    ]
