# Generated by Django 4.1.7 on 2023-03-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0015_rename_ownershipprove_realestate_ownershipproof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='ownerShipProof',
        ),
    ]
