# Generated by Django 4.1.7 on 2023-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0016_remove_realestate_image1_remove_realestate_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('Proof', 'Proof'), ('View', 'View')], default='View', max_length=8),
        ),
    ]
