# Generated by Django 4.1.7 on 2023-03-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0017_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
